gui:
  language: en
  border: rounded
  theme:
      activeBorderColor:
          - "#5ef1ff"
      inactiveBorderColor:
          - "#7b8496"
      searchingActiveBorderColor:
          - "#ff5ef1"
      optionsTextColor:
          - "#3c4048"
      selectedLineBgColor:
          - "#3c4048"
      cherryPickedCommitBgColor:
          - "#3c4048"
      cherryPickedCommitFgColor:
          - "#ff5ea0"
      unstagedChangesColor:
          - "#ffbd5e"
      defaultFgColor:
          - "#ffffff"
  expandFocusedSidePanel: true
  mainPanelSplitMode: vertical
  showFileTree: false
  nerdFontsVersion: "3"
  scrollOffMargin: 3
  mouseEvents: false
  fileTreeSortOrder: foldersFirst
  showRandomTip: false
  spinner:
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
    rate: 50
git:
  autoForwardBranches: none
  diffRenderers:
    - command: delta --dark --paging=never
  parseEmoji: true
os:
  editPreset: 'nvim'
notARepository: skip
disableStartupPopups: false
