general {
    border_size = 0
    col.active_border = rgba(88888888)

    gaps_in = 0
    gaps_out = 0

    resize_on_border = true
    extend_border_grab_area = 15
}


decoration {
    rounding = 0
    rounding_power = 4

    active_opacity = 1.0
    inactive_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.2

    blur {
        enabled = true
        size = 7
        passes = 5
        noise = 0.01
        contrast = 1.0
        brightness = 1.1
        vibrancy = 1.1
        new_optimizations = true
        ignore_opacity = false
    }

    shadow {
        enabled = false
    }
}
