# Set prefix to alt + space
set -g prefix M-Space
unbind C-b
bind M-Space send-prefix

# Set popup border style to rounded
set -g popup-border-lines rounded

# Remap split panes using to h and v
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# Fast reload
bind r source-file ~/.config/tmux/tmux.conf

# Statusline
set -g status-position top
set -g status-interval 1
set -g status-style bg=default

# Mouse scroll
set -g mouse on

# vi mode in scroll
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Resize
bind -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'resize-pane -L 5'
bind -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'resize-pane -D 5'
bind -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'resize-pane -U 5'
bind -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'resize-pane -R 5'

bind-key -T copy-mode-vi M-h resize-pane -L 5
bind-key -T copy-mode-vi M-j resize-pane -D 5
bind-key -T copy-mode-vi M-k resize-pane -U 5
bind-key -T copy-mode-vi M-l resize-pane -R 5

bind g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" lazygit
bind d display-popup -E -w 90% -h 90% -d "#{pane_current_path}" lazydocker

# Popup terminal
# bind-key -n 'C-\' if-shell -F '#{==:#{session_name},floating}' {
#     detach-client
# } {
#     display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "tmux attach-session -t floating || tmux new-session -s floating"
# }

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
run '~/.tmux/plugins/tpm/tpm'
