source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/animation.conf
source = ~/.config/hypr/conf/decoration.conf

monitor = ,2880x1800@120, auto, 1.666

exec-once = ${TERMINAL} & hyprpanel & hypridle & hyprpaper
exec-once = hyprctl setcursor ${CURSOR_THEME} ${CURSOR_SIZE}
exec-once = [workspace 2 silent] chromium
exec-once = [workspace 10 silent] Telegram

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, ru
    kb_options = grp:alt_shift_toggle

    follow_mouse = 1

    repeat_delay = 200
    repeat_rate = 50

    touchpad {
        natural_scroll = true
        scroll_factor = 0.1
    }

}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true
    # font_family = 
    # splash_font_family =
}

cursor {
    hide_on_key_press = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
    # enforce_permissions = 1
}

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow















# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

